config/routes.rb
Rails.application.routes.draw do
  root "articles#index"

  resources :articles do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments

    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 5 }
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    def index
        @articles = Article.all
    end

    def show
        @article = Article.find(params[:id])
    end

    def new
        @article = Article.new
    end

    def create
        @article = Article.new(article_params)

        if @article.save
            redirect_to @article
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @article = Article.find(params[:id])
    end

    def update
        @article = Article.find(params[:id])
        if @article.update(article_params)
            redirect_to @article
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @article = Article.find(params[:id])
        @article.destroy

        redirect_to root_path, status: :see_other
    end

    private
    def article_params
        params.require(:article).permit(:title, :body)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    def index
    end

    def show
    end

    def new
    end

    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        redirect_to article_path(@article)
    end

    def edit
    end

    def update
    end

    def destroy
    end

    private
    def comment_params
        params.require(:comment).permit(:commenter, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |f| %>
    <div>
       <%= f.label :title %><br>
       <%= f.text_field :title %>
       <% article.errors.full_messages_for(:title).each do |m| %>
        <div><%= m %></div>
        <% end %>
    </div>

    <div>
    <%= f.label :body %><br>
    <%= f.text_field :body %>
    <% article.errors.full_messages_for(:body).each do |m| %>
     <div><%= m %></div>
     <% end %>
    </div>

    <div>
        <%= f.submit %>
    </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editar um artigo</h1>

<%= render "form", article: @article %>

<h2><%= @article.title %></h2>

<p><%= @article.body %></p>

<ul>
    <li><%= link_to "Editar", edit_article_path(@article) %></li>
</ul>

app/views/articles/index.html.erb
<h1>Artigos</h1>

<ul>
    <% @articles.each do |a| %>
        <li>
            <%= link_to a.title, a %>
        </li>
    <% end %>
</ul>

<%= link_to "Novo artigo", new_article_path %>

app/views/articles/new.html.erb
<h1>Novo Artigo</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<p><%= @article.body %></p>

<ul>
    <%= link_to "Editar", edit_article_path(@article) %>
    <%= link_to "Deletar", article_path(@article), data: {
        turbo_method: :delete,
        turbo_confirm: "Você tem certeza que deseja deletar?"
    } %>
</ul>

<h2>Comentários</h2>
<% @article.comments.each do |c| %>
    <p>
        <strong>Comentado por:</strong>
        <%= c.commenter %>
    </p>

    <p>
        <strong>Comentário:</strong>
        <%= c.body %>
    </p>
    <% end %>

<h2>Adicione um comentário</h2>
<%= form_with model: [ @article, @article.comments.build ] do |f| %>
    <p>
        <%= f.label :commenter %><br>
        <%= f.text_field :commenter %>
    </p>
    <p>
        <%= f.label :body %><br>
        <%= f.text_area :body %>
    </p>
    <p>
        <%= f.submit %>
    </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>